INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Deira',
 '["Abu Hail", "Al Buteen", "Al Dhagaya", "Al Garhoud", "Al Hamriya Port", "Al Khabisi", "Al Mamzar", "Al Mizhar", "Al Mizhar 1", "Al Mizhar 2", "Al Muraqqabat", "Al Murar", "Al Muteena", "Al Nahda", "Al Nahda 1", "Al Nahda 2", "Al Qusais", "Al Qusais 1", "Al Qusais 2", "Al Qusais 3", "Al Qusais Industrial Area", "Al Qusais Industrial Area 1", "Al Qusais Industrial Area 2", "Al Qusais Industrial Area 3", "Al Qusais Industrial Area 4", "Al Qusais Industrial Area 5", "Al Ras", "Al Rashidiya", "Al Rigga", "Al Sabkha", "Al Twar", "Al Twar 1", "Al Twar 2", "Al Twar 3", "Al Waheda", "Ayal Nasir", "Corniche Deira", "Hor Al Anz", "Hor Al Anz East", "Mirdif", "Muhaisnah", "Muhaisnah 1", "Muhaisnah 2", "Muhaisnah 3", "Muhaisnah 4", "Naif", "Oud Al Muteena", "Port Saeed", "Rigga Al Buteen", "Umm Ramool"]'::jsonb,
 'UAE',
 'Dubai');

INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Bur Dubai',
 '["Al Karama", "Al Bada", "Al Fahidi", "Al Hudaiba", "Al Jafiliya", "Al Mankhool", "Al Mina", "Al Raffa", "Al Shindagha", "Al Souk Al Kabir", "Bur Dubai", "Oud Metha", "Zabeel", "Zabeel 1", "Zabeel 2", "Trade Centre", "Trade Centre 1", "Trade Centre 2", "Jaddaf Waterfront", "Dubai Festival City", "Dubai Healthcare City", "Ras Al Khor", "Ras Al Khor Industrial Area", "Ras Al Khor Industrial Area 1", "Ras Al Khor Industrial Area 2", "Ras Al Khor Industrial Area 3", "Nad Al Hamar", "Nad Shamma", "Al Aweer", "Al Aweer 1", "Al Aweer 2", "Al Khawaneej", "Al Khawaneej 1", "Al Khawaneej 2", "International City", "Culture Village", "Business Bay", "Downtown Dubai", "Dubai Design District", "Bu Kadra", "Al Wasl", "Al Safa", "Al Safa 1", "Al Safa 2", "Jumeirah", "Umm Suqeim", "Umm Suqeim 1", "Umm Suqeim 2", "Umm Suqeim 3", "Al Manara", "Umm Al Sheif", "Al Barsha", "Al Barsha 1", "Al Barsha 2", "Al Barsha 3", "Al Barsha South", "Al Barsha South 1", "Al Barsha South 2", "Al Barsha South 3", "Al Barsha South 4", "Al Barsha South 5", "Al Sufouh", "Al Sufouh 1", "Al Sufouh 2", "Al Thanyah", "Al Thanyah 1", "Al Thanyah 2", "Al Thanyah 3", "Al Thanyah 4", "Al Thanyah 5", "Emirates Hills", "The Springs", "The Meadows", "The Lakes", "The Greens", "The Views", "Dubai Marina", "Jumeirah Lake Towers", "Jumeirah Islands", "Jumeirah Park", "Jumeirah Village Circle", "Jumeirah Village Triangle", "Dubai Investments Park", "Al Furjan", "Discovery Gardens", "Jebel Ali", "Jebel Ali Industrial Area", "Jebel Ali Palm", "Arabian Ranches", "Dubai Hills Estate", "Wadi Al Safa", "Wadi Al Safa 2", "Wadi Al Safa 3", "Wadi Al Safa 4", "Wadi Al Safa 5", "Wadi Al Safa 6", "Wadi Al Safa 7", "Al Hebiah", "Al Hebiah 1", "Al Hebiah 2", "Al Hebiah 3", "Al Hebiah 4", "Al Hebiah 5", "Al Hebiah 6", "Al Yufrah", "Al Yufrah 1", "Al Yufrah 2", "Al Yufrah 3", "Al Yufrah 4", "Al Eyas", "Madinat Al Mataar", "Me''aisem", "Me''aisem 1", "Me''aisem 2", "Mina Jebel Ali", "Saih Shuaib", "Saih Shuaib 1", "Saih Shuaib 2", "Saih Shuaib 3", "Saih Shuaib 4", "Al Yalayis", "Al Yalayis 1", "Al Yalayis 2", "Al Yalayis 3", "Al Yalayis 4", "Al Yalayis 5", "Hassyan", "Hassyan 1", "Hassyan 2", "Al Lisaili", "Al Marqadh", "Lehbab", "Lehbab 1", "Lehbab 2", "Margham", "Murquab", "Saih Al Salam", "Umm Nahad", "Umm Nahad 1", "Umm Nahad 2", "Umm Nahad 3", "Umm Nahad 4", "Hatta", "Al Rowaiyah", "Al Ruwayyah", "Al Wajeh", "Al Wohoosh", "Enkhali", "Ghadeer Al Tair", "Grayteesah", "Hele''ew", "Nazwah", "Reeh", "Saih Al Danal", "Saih Al Sidirah", "Saih Fuh", "Saih Shua''a", "Tayy", "Wadi Al Amardi", "Wadi Al Shabak", "Al Ghena", "Al Meryal"]'::jsonb,
 'UAE',
 'Dubai');