INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Deira',
 '[
  {"name": "Abu Hail", "surcharge": 0}, {"name": "Al Baraha", "surcharge": 0}, {"name": "Al Buteen", "surcharge": 0},
  {"name": "Al Dhagaya", "surcharge": 0}, {"name": "Al Hamriya Port", "surcharge": 0}, {"name": "Al Khabisi", "surcharge": 0},
  {"name": "Al Mamzar", "surcharge": 0}, {"name": "Al Mizhar", "surcharge": 0}, {"name": "Al Mizhar 1", "surcharge": 0},
  {"name": "Al Mizhar 2", "surcharge": 0}, {"name": "Al Muraqqabat", "surcharge": 0}, {"name": "Al Murar", "surcharge": 0},
  {"name": "Al Muteena", "surcharge": 0}, {"name": "Al Nahda", "surcharge": 0}, {"name": "Al Nahda 1", "surcharge": 0},
  {"name": "Al Nahda 2", "surcharge": 0}, {"name": "Al Qusais", "surcharge": 0}, {"name": "Al Qusais 1", "surcharge": 0},
  {"name": "Al Qusais 2", "surcharge": 0}, {"name": "Al Qusais 3", "surcharge": 0}, {"name": "Al Qusais Industrial Area", "surcharge": 0},
  {"name": "Al Qusais Industrial Area 1", "surcharge": 0}, {"name": "Al Qusais Industrial Area 2", "surcharge": 0},
  {"name": "Al Qusais Industrial Area 3", "surcharge": 0}, {"name": "Al Qusais Industrial Area 4", "surcharge": 0},
  {"name": "Al Qusais Industrial Area 5", "surcharge": 0}, {"name": "Al Ras", "surcharge": 0}, {"name": "Al Rashidiya", "surcharge": 0},
  {"name": "Al Rigga", "surcharge": 0}, {"name": "Al Sabkha", "surcharge": 0}, {"name": "Al Twar", "surcharge": 0},
  {"name": "Al Twar 1", "surcharge": 0}, {"name": "Al Twar 2", "surcharge": 0}, {"name": "Al Twar 3", "surcharge": 0},
  {"name": "Al Waheda", "surcharge": 0}, {"name": "Ayal Nasir", "surcharge": 0}, {"name": "Corniche Deira", "surcharge": 0},
  {"name": "Hor Al Anz", "surcharge": 0}, {"name": "Hor Al Anz East", "surcharge": 0}, {"name": "Mirdif", "surcharge": 0},
  {"name": "Muhaisnah", "surcharge": 0}, {"name": "Muhaisnah 1", "surcharge": 0}, {"name": "Muhaisnah 2", "surcharge": 0},
  {"name": "Muhaisnah 3", "surcharge": 0}, {"name": "Muhaisnah 4", "surcharge": 0}, {"name": "Naif", "surcharge": 0},
  {"name": "Oud Al Muteena", "surcharge": 0}, {"name": "Port Saeed", "surcharge": 0}, {"name": "Rigga Al Buteen", "surcharge": 0}
 ]'::jsonb,
 'UAE',
 'Dubai');

INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Bur Dubai',
 '[
  {"name": "Al Aweer", "surcharge": 0}, {"name": "Al Aweer 1", "surcharge": 0}, {"name": "Al Aweer 2", "surcharge": 0},
  {"name": "Al Bada", "surcharge": 0}, {"name": "Al Barsha", "surcharge": 0}, {"name": "Al Barsha 1", "surcharge": 0},
  {"name": "Al Barsha 2", "surcharge": 0}, {"name": "Al Barsha 3", "surcharge": 0}, {"name": "Al Barsha South", "surcharge": 0},
  {"name": "Al Barsha South 1", "surcharge": 0}, {"name": "Al Barsha South 2", "surcharge": 0}, {"name": "Al Barsha South 3", "surcharge": 0},
  {"name": "Al Barsha South 4", "surcharge": 0}, {"name": "Al Barsha South 5", "surcharge": 0}, {"name": "Al Eyas", "surcharge": 0},
  {"name": "Al Fahidi", "surcharge": 0}, {"name": "Al Furjan", "surcharge": 0}, {"name": "Al Garhoud", "surcharge": 0},
  {"name": "Al Ghena", "surcharge": 0}, {"name": "Al Guoz", "surcharge": 0}, {"name": "Al Hebiah", "surcharge": 0},
  {"name": "Al Hebiah 1", "surcharge": 0}, {"name": "Al Hebiah 2", "surcharge": 0}, {"name": "Al Hebiah 3", "surcharge": 0},
  {"name": "Al Hebiah 4", "surcharge": 0}, {"name": "Al Hebiah 5", "surcharge": 0}, {"name": "Al Hebiah 6", "surcharge": 0},
  {"name": "Al Hudaiba", "surcharge": 0}, {"name": "Al Jafiliya", "surcharge": 0}, {"name": "Al Karama", "surcharge": 0},
  {"name": "Al Khawaneej", "surcharge": 0}, {"name": "Al Khawaneej 1", "surcharge": 0}, {"name": "Al Khawaneej 2", "surcharge": 0},
  {"name": "Al Lesaily", "surcharge": 0}, {"name": "Al Lisaili", "surcharge": 0}, {"name": "Al Manara", "surcharge": 0},
  {"name": "Al Mankhool", "surcharge": 0}, {"name": "Al Marqadh", "surcharge": 0}, {"name": "Al Meryal", "surcharge": 0},
  {"name": "Al Mina", "surcharge": 0}, {"name": "Al Quoz", "surcharge": 0}, {"name": "Al Quoz 1", "surcharge": 0},
  {"name": "Al Quoz 2", "surcharge": 0}, {"name": "Al Quoz 3", "surcharge": 0}, {"name": "Al Quoz 4", "surcharge": 0},
  {"name": "Al Quoz Industrial Area", "surcharge": 0}, {"name": "Al Quoz Industrial Area 1", "surcharge": 0},
  {"name": "Al Quoz Industrial Area 2", "surcharge": 0}, {"name": "Al Quoz Industrial Area 3", "surcharge": 0},
  {"name": "Al Quoz Industrial Area 4", "surcharge": 0}, {"name": "Al Raffa", "surcharge": 0}, {"name": "Al Rowaiyah", "surcharge": 0},
  {"name": "Al Rowaiyah 1", "surcharge": 0}, {"name": "Al Rowaiyah 2", "surcharge": 0}, {"name": "Al Rowaiyah 3", "surcharge": 0},
  {"name": "Al Ruwayyah", "surcharge": 0}, {"name": "Al Safa", "surcharge": 0}, {"name": "Al Safa 1", "surcharge": 0},
  {"name": "Al Safa 2", "surcharge": 0}, {"name": "Al Shindagha", "surcharge": 0}, {"name": "Al Souk Al Kabir", "surcharge": 0},
  {"name": "Al Sufouh", "surcharge": 0}, {"name": "Al Sufouh 1", "surcharge": 0}, {"name": "Al Sufouh 2", "surcharge": 0},
  {"name": "Al Thanyah", "surcharge": 0}, {"name": "Al Thanyah 1", "surcharge": 0}, {"name": "Al Thanyah 2", "surcharge": 0},
  {"name": "Al Thanyah 3", "surcharge": 0}, {"name": "Al Thanyah 4", "surcharge": 0}, {"name": "Al Thanyah 5", "surcharge": 0},
  {"name": "Al Wajeh", "surcharge": 0}, {"name": "Al Wasl", "surcharge": 0}, {"name": "Al Wohoosh", "surcharge": 0},
  {"name": "Al Yalayis", "surcharge": 0}, {"name": "Al Yalayis 1", "surcharge": 0}, {"name": "Al Yalayis 2", "surcharge": 0},
  {"name": "Al Yalayis 3", "surcharge": 0}, {"name": "Al Yalayis 4", "surcharge": 0}, {"name": "Al Yalayis 5", "surcharge": 0},
  {"name": "Al Yufrah", "surcharge": 0}, {"name": "Al Yufrah 1", "surcharge": 0}, {"name": "Al Yufrah 2", "surcharge": 0},
  {"name": "Al Yufrah 3", "surcharge": 0}, {"name": "Al Yufrah 4", "surcharge": 0}, {"name": "Arabian Ranches", "surcharge": 0},
  {"name": "Bu Kadra", "surcharge": 0}, {"name": "Bur Dubai", "surcharge": 0}, {"name": "Business Bay", "surcharge": 0},
  {"name": "Culture Village", "surcharge": 0}, {"name": "Discovery Gardens", "surcharge": 0}, {"name": "Downtown Dubai", "surcharge": 0},
  {"name": "Dubai Design District", "surcharge": 0}, {"name": "Dubai Festival City", "surcharge": 0},
  {"name": "Dubai Healthcare City", "surcharge": 0}, {"name": "Dubai Hills Estate", "surcharge": 0},
  {"name": "Dubai Investments Park", "surcharge": 0}, {"name": "Dubai Marina", "surcharge": 0}, {"name": "Emirates Hills", "surcharge": 0},
  {"name": "Enkhali", "surcharge": 0}, {"name": "Ghadeer Al Tair", "surcharge": 0}, {"name": "Grayteesah", "surcharge": 0},
  {"name": "Hassyan", "surcharge": 0}, {"name": "Hassyan 1", "surcharge": 0}, {"name": "Hassyan 2", "surcharge": 0},
  {"name": "Hatta", "surcharge": 0}, {"name": "Hele''ew", "surcharge": 0}, {"name": "International City", "surcharge": 0},
  {"name": "Jaddaf Waterfront", "surcharge": 0}, {"name": "Jebel Ali", "surcharge": 0}, {"name": "Jebel Ali 1", "surcharge": 0},
  {"name": "Jebel Ali 2", "surcharge": 0}, {"name": "Jebel Ali Industrial", "surcharge": 0},
  {"name": "Jebel Ali Industrial Area", "surcharge": 0}, {"name": "Jebel Ali Palm", "surcharge": 0}, {"name": "Jumeirah", "surcharge": 0},
  {"name": "Jumeirah Islands", "surcharge": 0}, {"name": "Jumeirah Lake Towers", "surcharge": 0}, {"name": "Jumeirah Park", "surcharge": 0},
  {"name": "Jumeirah Village Circle", "surcharge": 0}, {"name": "Jumeirah Village Triangle", "surcharge": 0},
  {"name": "Lehbab", "surcharge": 0}, {"name": "Lehbab 1", "surcharge": 0}, {"name": "Lehbab 2", "surcharge": 0},
  {"name": "Madinat Al Mataar", "surcharge": 0}, {"name": "Margham", "surcharge": 0}, {"name": "Meadows", "surcharge": 0},
  {"name": "Me''aisem", "surcharge": 0}, {"name": "Me''aisem 1", "surcharge": 0}, {"name": "Me''aisem 2", "surcharge": 0},
  {"name": "Mina Jebel Ali", "surcharge": 0}, {"name": "Murquab", "surcharge": 0}, {"name": "Nad Al Hamar", "surcharge": 0},
  {"name": "Nad Shamma", "surcharge": 0}, {"name": "Nazwah", "surcharge": 0}, {"name": "Oud Metha", "surcharge": 0},
  {"name": "Ras Al Khor", "surcharge": 0}, {"name": "Ras Al Khor Industrial Area", "surcharge": 0},
  {"name": "Ras Al Khor Industrial Area 1", "surcharge": 0}, {"name": "Ras Al Khor Industrial Area 2", "surcharge": 0},
  {"name": "Ras Al Khor Industrial Area 3", "surcharge": 0}, {"name": "Reeh", "surcharge": 0}, {"name": "Saih Al Danal", "surcharge": 0},
  {"name": "Saih Al Salam", "surcharge": 0}, {"name": "Saih Al Sidirah", "surcharge": 0}, {"name": "Saih Fuh", "surcharge": 0},
  {"name": "Saih Shua''a", "surcharge": 0}, {"name": "Saih Shuaib", "surcharge": 0}, {"name": "Saih Shuaib 1", "surcharge": 0},
  {"name": "Saih Shuaib 2", "surcharge": 0}, {"name": "Saih Shuaib 3", "surcharge": 0}, {"name": "Saih Shuaib 4", "surcharge": 0},
  {"name": "Tayy", "surcharge": 0}, {"name": "The Gardens", "surcharge": 0}, {"name": "The Greens", "surcharge": 0},
  {"name": "The Lakes", "surcharge": 0}, {"name": "The Springs", "surcharge": 0}, {"name": "The Views", "surcharge": 0},
  {"name": "Trade Centre", "surcharge": 0}, {"name": "Trade Centre 1", "surcharge": 0}, {"name": "Trade Centre 2", "surcharge": 0},
  {"name": "Umm Al Sheif", "surcharge": 0}, {"name": "Umm Nahad", "surcharge": 0}, {"name": "Umm Nahad 1", "surcharge": 0},
  {"name": "Umm Nahad 2", "surcharge": 0}, {"name": "Umm Nahad 3", "surcharge": 0}, {"name": "Umm Nahad 4", "surcharge": 0},
  {"name": "Umm Ramool", "surcharge": 0}, {"name": "Umm Suqeim", "surcharge": 0}, {"name": "Umm Suqeim 1", "surcharge": 0},
  {"name": "Umm Suqeim 2", "surcharge": 0}, {"name": "Umm Suqeim 3", "surcharge": 0}, {"name": "Wadi Al Amardi", "surcharge": 0},
  {"name": "Wadi Al Safa", "surcharge": 0}, {"name": "Wadi Al Safa 2", "surcharge": 0}, {"name": "Wadi Al Safa 3", "surcharge": 0},
  {"name": "Wadi Al Safa 4", "surcharge": 0}, {"name": "Wadi Al Safa 5", "surcharge": 0}, {"name": "Wadi Al Safa 6", "surcharge": 0},
  {"name": "Wadi Al Safa 7", "surcharge": 0}, {"name": "Wadi Al Shabak", "surcharge": 0}, {"name": "Zabeel", "surcharge": 0},
  {"name": "Zabeel 1", "surcharge": 0}, {"name": "Zabeel 2", "surcharge": 0}
 ]'::jsonb,
 'UAE',
 'Dubai');





 INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Abu Dhabi Island',
 '[
  {"name": "Al Bateen", "surcharge": 0}, {"name": "Al Dana", "surcharge": 0}, {"name": "Al Etihad", "surcharge": 0},
  {"name": "Al Falah Street", "surcharge": 0}, {"name": "Al Hosn", "surcharge": 0}, {"name": "Al Karamah", "surcharge": 0},
  {"name": "Al Khalidiyah", "surcharge": 0}, {"name": "Al Manhal", "surcharge": 0}, {"name": "Al Maqtaa", "surcharge": 0},
  {"name": "Al Markaziyah", "surcharge": 0}, {"name": "Al Mina", "surcharge": 0}, {"name": "Al Muroor", "surcharge": 0},
  {"name": "Al Mushrif", "surcharge": 0}, {"name": "Al Muzoon", "surcharge": 0}, {"name": "Al Nahyan", "surcharge": 0},
  {"name": "Al Ras Al Akhdar", "surcharge": 0}, {"name": "Al Rowdah", "surcharge": 0}, {"name": "Al Wahda", "surcharge": 0},
  {"name": "Al Zaab", "surcharge": 0}, {"name": "Al Zahraa", "surcharge": 0}, {"name": "Al Zahiyah (Tourist Club Area)", "surcharge": 0},
  {"name": "Bain Al Jisrain (Between Two Bridges)", "surcharge": 0}, {"name": "Corniche Area", "surcharge": 0},
  {"name": "Emirates Palace", "surcharge": 0}, {"name": "Hadbat Al Zaafran", "surcharge": 0}, {"name": "Hamdan Street", "surcharge": 0},
  {"name": "Khor Al Bateen", "surcharge": 0}, {"name": "Madinat Zayed (Downtown)", "surcharge": 0}, {"name": "Marina Village", "surcharge": 0},
  {"name": "Qasr El Bahr", "surcharge": 0}, {"name": "Qasr El Shatie", "surcharge": 0}
 ]'::jsonb,
 'UAE',
 'Abu Dhabi');

INSERT INTO public."deliveryLocations" (district, sublocalities, country, city) VALUES
('Abu Dhabi Mainland & Islands',
 '[
  {"name": "Abu Dhabi Gate City (Officers City)", "surcharge": 0}, {"name": "Abu Dhabi International Airport", "surcharge": 0},
  {"name": "Al Bahia", "surcharge": 0}, {"name": "Al Bandar", "surcharge": 0}, {"name": "Al Falah", "surcharge": 0},
  {"name": "Al Forsan Village", "surcharge": 0}, {"name": "Al Ghadeer", "surcharge": 0}, {"name": "Al Gurm", "surcharge": 0},
  {"name": "Al Jubail Island", "surcharge": 0}, {"name": "Al Maryah Island", "surcharge": 0}, {"name": "Al Muneera", "surcharge": 0},
  {"name": "Al Raha Beach", "surcharge": 0}, {"name": "Al Raha Gardens", "surcharge": 0}, {"name": "Al Rahba", "surcharge": 0},
  {"name": "Al Reef", "surcharge": 0}, {"name": "Al Reem Island", "surcharge": 0}, {"name": "Al Samha", "surcharge": 0},
  {"name": "Al Shahama", "surcharge": 0}, {"name": "Al Shamkha", "surcharge": 0}, {"name": "Al Shawamekh", "surcharge": 0},
  {"name": "Al Wathba", "surcharge": 0}, {"name": "Al Zeina", "surcharge": 0}, {"name": "Baniyas", "surcharge": 0},
  {"name": "Bloom Gardens", "surcharge": 0}, {"name": "Dalma Island", "surcharge": 0}, {"name": "Ghantoot", "surcharge": 0},
  {"name": "Golf Gardens", "surcharge": 0}, {"name": "Hudayriyat Island", "surcharge": 0}, {"name": "Hydra Village", "surcharge": 0},
  {"name": "Khalifa City", "surcharge": 0}, {"name": "Masdar City", "surcharge": 0}, {"name": "Mohammed Bin Zayed City (MBZ City)", "surcharge": 0},
  {"name": "Mussafah", "surcharge": 0}, {"name": "Mussafah Industrial Area", "surcharge": 0}, {"name": "Nurai Island", "surcharge": 0},
  {"name": "Ramhan Island", "surcharge": 0}, {"name": "Saadiyat Island", "surcharge": 0}, {"name": "Sas Al Nakhl Village", "surcharge": 0},
  {"name": "Shakhbout City", "surcharge": 0}, {"name": "Sweihan", "surcharge": 0}, {"name": "Yas Island", "surcharge": 0},
  {"name": "Zayed City (Madinat Al Riyad)", "surcharge": 0}, {"name": "Zayed Military City", "surcharge": 0}
 ]'::jsonb,
 'UAE',
 'Abu Dhabi');