version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kloi
      - REDIS_URL=redis://redis:6379
      - STRIPE_SECRET_KEY=replace_me
      - SENDGRID_API_KEY=replace_me
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    networks:
      - kloi_net

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: kloi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kloi_net

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - kloi_net

volumes:
  db_data:

networks:
  kloi_net:
    driver: bridge
